### ISSUE TITLE
Problem building Core Framework on Ubuntu 14.04 on Beaglebone Black for Sub$100

### ISSUE THREAD

**Issue by sbierly** [RedhawkSDR/framework-core#28]
Hi there.  Help would be greatly appreciated, I believe I have followed the Sub$100 Project instructions to the letter, but the build always fails the same way.  I have checked everything in the instructions 3 times. After several failed attempts, and trying both "git checkout 1.10.0" (per the instructions) and 1.10.1 (per the latest), here is the log starting with the configure showing the incremental build and error, as well as the Ubuntu and Boost versions:

ubuntu@arm:~/framework-core/src$ ./configure --disable-java --with-boost-libdir=/usr/lib/arm-linux-gnueabihf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking for ossie home... /home/ubuntu/redhawk
configure: using /home/ubuntu/redhawk as installation prefix
checking for sdr root... /home/ubuntu/redhawk/sdr
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking how to print strings... printf
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert armv7l-unknown-linux-gnueabihf file names to armv7l-unknown-linux-gnueabihf format... func_convert_file_noop
checking how to convert armv7l-unknown-linux-gnueabihf file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking gr_libdir_suffix... 
checking whether to append 64 to libdir... no
checking for omniORB4... yes
checking for boostlib >= 1.35... yes
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
checking whether the Boost::Serialization library is available... yes
checking for exit in -lboost_serialization... yes
checking whether the Boost::Regex library is available... yes
checking for exit in -lboost_regex... yes
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread... yes
checking whether the Boost::Date_Time library is available... yes
checking for exit in -lboost_date_time... yes
checking for Expat XML Parser headers in /usr/include... found
checking for Expat XML Parser libraries... found
checking for Expat XML Parser... yes
checking if Expat XML Parser version is >= 1.95.8... yes
checking for OMNIORB... yes
checking for OMNITHREAD... yes
checking for OMNIDYNAMIC... yes
checking for COS library... yes
checking for OMNICOS... yes
checking for omniidl... omniidl
checking for default IDL path... /usr/share/idl/omniORB
checking for xsdcxx... xsdcxx
checking xsd version... 3.3.0
checking xsd/cxx/config.hxx usability... yes
checking xsd/cxx/config.hxx presence... yes
checking for xsd/cxx/config.hxx... yes
checking for xmlcatalog... xmlcatalog
checking for a sed that does not truncate output... (cached) /bin/sed
checking for python install scheme... home
checking for LOG4CXX... yes
checking to see if tracing should be enabled... no
checking to see if domain persistence should be enabled... no
checking whether make supports nested variables... (cached) yes
checking if xml parsers should perform validation... yes
checking for a Python interpreter with version >= 2.3... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking if python backports are necessary... "no"
checking for python module logging ... yes
checking for python module subprocess... yes
checking for python module omniORB... yes
checking for python module omniidl... yes
checking for sys/wait.h that is POSIX.1 compatible... (cached) yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking uuid/uuid.h usability... yes
checking uuid/uuid.h presence... yes
checking for uuid/uuid.h... yes
checking for uuid_generate in -luuid... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating ossie.pc
config.status: creating acinclude/Makefile
config.status: creating etc/Makefile
config.status: creating omnijni/Makefile
config.status: creating omnijni/include/omnijni/Makefile
config.status: creating omnijni/src/cpp/Makefile
config.status: creating omnijni/src/cpp/CORBA/Makefile
config.status: creating omnijni/src/java/Makefile
config.status: creating omnijni/src/python/omnijni/Makefile
config.status: creating control/Makefile
config.status: creating control/parser/Makefile
config.status: creating control/framework/Makefile
config.status: creating control/sdr/Makefile
config.status: creating control/sdr/dommgr/Makefile
config.status: creating control/sdr/devmgr/Makefile
config.status: creating base/Makefile
config.status: creating base/framework/python/Makefile
config.status: creating base/framework/java/Makefile
config.status: creating base/framework/java/jni/Makefile
config.status: creating base/framework/java/jni/COS/Makefile
config.status: creating base/framework/java/ossie/Makefile
config.status: creating base/framework/idl/Makefile
config.status: creating base/framework/Makefile
config.status: creating base/include/ossie/Makefile
config.status: creating base/include/Makefile
config.status: creating base/parser/Makefile
config.status: creating idl/Makefile
config.status: creating xml/Makefile
config.status: creating tools/LogEventAppender/Makefile
config.status: creating testing/Makefile
config.status: creating testing/_unitTestHelpers/buildconfig.py
config.status: creating testing/sdr/dev/devices/ExecutableDevice/Makefile
config.status: creating testing/sdr/dev/devices/BasicTestDevice_cpp/BasicTestDevice_cpp_impl1/Makefile
config.status: creating testing/sdr/dev/devices/BasicTestDevice_java/java/Makefile
config.status: creating testing/sdr/dev/devices/CppTestDevice/cpp/Makefile
config.status: creating testing/sdr/dev/devices/BasicDevWithExecParam_cpp/BasicDevWithExecParam_cpp_impl1/Makefile
config.status: creating testing/sdr/dev/devices/JavaTestDevice/java/Makefile
config.status: creating testing/sdr/dev/devices/SimpleDevice/SimpleDevice_cpp_impl1/Makefile
config.status: creating testing/sdr/dev/devices/props_test_device/props_test_device_cpp_impl1/Makefile
config.status: creating testing/sdr/dev/devices/issue_111_cpp/cpp/Makefile
config.status: creating testing/sdr/dev/devices/issue_111_java/java/Makefile
config.status: creating testing/sdr/dev/devices/PersonaDevice/cpp/Makefile
config.status: creating testing/sdr/dev/devices/ProgrammableDevice/cpp/Makefile
config.status: creating testing/sdr/dev/services/BasicService_java/java/Makefile
config.status: creating testing/sdr/dom/components/CppCallbacks/cpp/Makefile
config.status: creating testing/sdr/dom/components/TestCppProps/Makefile
config.status: creating testing/sdr/dom/components/TestJavaProps/Makefile
config.status: creating testing/sdr/dom/components/TestLegacyJavaProps/Makefile
config.status: creating testing/sdr/dom/components/TestJavaPropsRange/java/Makefile
config.status: creating testing/sdr/dom/components/linkedLibraryTest/Makefile
config.status: creating testing/sdr/dom/components/TestCppsoftpkgDeps/Makefile
config.status: creating testing/sdr/dom/components/javaDep/javaDep/Makefile
config.status: creating testing/sdr/dom/components/HardLimit/HardLimit_java_impl1/Makefile
config.status: creating testing/sdr/dom/components/SimpleComponent/SimpleComponent_cpp_impl1/Makefile
config.status: creating testing/sdr/dom/components/BasicAC/basicac_java_impl1/Makefile
config.status: creating testing/sdr/dom/components/BasicAC/BasicAC_cpp_impl1/Makefile
config.status: creating testing/sdr/dom/components/MessageReceiverCpp/Makefile
config.status: creating testing/sdr/dom/components/MessageSenderCpp/Makefile
config.status: creating testing/sdr/dom/components/EventSend/EventSend_java_impl1/Makefile
config.status: creating testing/sdr/dom/components/EventReceive/EventReceive_java_impl1/Makefile
config.status: creating testing/sdr/dom/components/PropertyChangeEventsCpp/Makefile
config.status: creating testing/sdr/dom/components/PropertyChangeEventsJava/PropertyChangeEventsJava_java_impl1/Makefile
config.status: creating testing/sdr/dom/components/ticket2093/cpp/Makefile
config.status: creating testing/sdr/dom/components/TestComplexProps/cpp/Makefile
config.status: creating testing/sdr/dom/components/TestComplexProps/java/Makefile
config.status: creating testing/sdr/dom/components/TestCppPropsRange/cpp/Makefile
config.status: creating testing/sdr/dom/components/TestAllPropTypes/cpp/Makefile
config.status: creating testing/sdr/dom/components/TestAllPropTypes/java/Makefile
config.status: creating testing/sdr/dom/components/TestLoggingAPI/cpp/Makefile
config.status: creating testing/sdr/dom/components/TestLoggingAPI/java/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
ubuntu@arm:~/framework-core/src$ make
Making all in acinclude
make[1]: Entering directory `/home/ubuntu/framework-core/src/acinclude'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/home/ubuntu/framework-core/src/acinclude'
Making all in etc
make[1]: Entering directory`/home/ubuntu/framework-core/src/etc'
  GEN      ld.so.conf.d/redhawk.conf
  GEN      profile.d/redhawk.sh
  GEN      profile.d/redhawk.csh
  GEN      profile.d/redhawk-sdrroot.sh
  GEN      profile.d/redhawk-sdrroot.csh
make[1]: Leaving directory `/home/ubuntu/framework-core/src/etc'
Making all in base
make[1]: Entering directory`/home/ubuntu/framework-core/src/base'
Making all in framework/idl
make[2]: Entering directory `/home/ubuntu/framework-core/src/base/framework/idl'
make  all-am
make[3]: Entering directory`/home/ubuntu/framework-core/src/base/framework/idl'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory`/home/ubuntu/framework-core/src/base/framework/idl'
make[2]: Leaving directory `/home/ubuntu/framework-core/src/base/framework/idl'
Making all in framework/python
make[2]: Entering directory`/home/ubuntu/framework-core/src/base/framework/python'
make  all-am
make[3]: Entering directory `/home/ubuntu/framework-core/src/base/framework/python'
python setup.py --quiet build
make[3]: Leaving directory`/home/ubuntu/framework-core/src/base/framework/python'
make[2]: Leaving directory `/home/ubuntu/framework-core/src/base/framework/python'
Making all in parser
make[2]: Entering directory`/home/ubuntu/framework-core/src/base/parser'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory`/home/ubuntu/framework-core/src/base/parser'
Making all in framework
make[2]: Entering directory `/home/ubuntu/framework-core/src/base/framework'
  CXX      libossiecf_la-Device_impl.lo
  CXX      libossiecf_la-PropertySet_impl.lo
  CXX      libossiecf_la-Logging_impl.lo
  CXX      libossiecf_la-Resource_impl.lo
  CXX      libossiecf_la-ThreadedComponent.lo
  CXX      libossiecf_la-ExecutableDevice_impl.lo
  CXX      libossiecf_la-LoadableDevice_impl.lo
LoadableDevice_impl.cpp: In member function 'virtual void LoadableDevice_impl::load(CF::FileSystem_ptr, const char*, CF::LoadableDevice::LoadType)':
LoadableDevice_impl.cpp:325:43: warning: ignoring return value of 'int chdir(const char*)', declared with attribute warn_unused_result [-Wunused-result]
                 chdir(currentPath.c_str());
                                           ^
LoadableDevice_impl.cpp:367:43: warning: ignoring return value of 'int chdir(const char*)', declared with attribute warn_unused_result [-Wunused-result]
                 chdir(currentPath.c_str());
                                           ^
  CXX      libossiecf_la-helperFunctions.lo
  CXX      libossiecf_la-POACreator.lo
  CXX      libossiecf_la-CorbaUtils.lo
  CXX      libossiecf_la-ORB.lo
  CXX      libossiecf_la-prop_helpers.lo
  CXX      libossiecf_la-MessageInterface.lo
  CXX      libossiecf_la-PropertyInterface.lo
  CXX      libossiecf_la-Service_impl.lo
  CXX      libossiecf_la-AnyUtils.lo
  CXX      libossiecf_la-loghelpers.lo
logging/loghelpers.cpp: In function 'std::string ossie::logging::_saveConfig(const string&)':
logging/loghelpers.cpp:408:43: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
         write( fd, fc.c_str(), fc.size() );
                                           ^
  CXX      libossiecf_la-rh_logger.lo
  CXX      libossiecf_la-RH_LogEventAppender.lo
  CXX      libossiecf_la-EventChannelSupport.lo
  CXXLD    libossiecf.la
libtool: link:`libossiecf_la-PortSupplier_impl.lo' is not a valid libtool object
make[2]: **\* [libossiecf.la] Error 1
make[2]: Leaving directory `/home/ubuntu/framework-core/src/base/framework'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/home/ubuntu/framework-core/src/base'
make: **\* [all-recursive] Error 1
ubuntu@arm:~/framework-core/src$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty
ubuntu@arm:~/framework-core/src$ dpkg -s libboost-dev | grep 'Version'
Version: 1.54.0.1ubuntu1

I'm hoping you will tell me I've done something stupid.  I really appreciate your help, I'm a systems guy, not a software guy, so this is a stretch for me.  

Thanks,
--Scott

**Comment by DrewCormier** [comment]
It appears that the file libossiecf_la-PortSupplier_impl.lo has become corrupt (possibly from an incomplete build).  Try deleting this file ("make distclean" should work) and starting over with the build.
