### ISSUE TITLE
Problems building framework-core master on Xilinx ZC706 

### ISSUE THREAD

**Issue by horn545** [RedhawkSDR/framework-core#31]
On CentOS6.7, Using Yocto Poky-Jethro in /opt/Yocto/poky-jethro-14.0.1
Added meta-xilinx recipes from https://github.com/Xilinx/meta-xilinx
Added openembedded-redhawk, edited all recipes to use SRCREV="${AUTOREV}"
Edited redhawk-core recipe to retrieve GIT repo from RedhawkSDR/framework-core; branch=master
Download and Unzip the Yocto 2.0.1 Buildtools to /opt/poky, source /opt/poky/2.0.1/environment-setup-x86_64-pokysdk-linux
Source /opt/Yocto/poky-jethro-14.0.1/oe-init-build-env
Add meta-xilinx, openembedded-redhawk to bblayers.conf
Select zc706-zynq7 hardware in local.conf
Execute bitbake core-image-minimal

Build of redhawk-core fails with missing headers in xsd/cxx/include
     | #include <xsd/cxx/config.hxx>
     | configure:19056: result: no
     | configure:19056: checking for xsd/cxx/config.hxx
     | configure:19056: result: no
     | configure:19060: error: missing XSD headers

Followed similar setup in Bagoulla feature-no-xsd-1.10 branch to add in XSD using GIT patch, remove XSD tests from configure.ac, remove XSD calls from control/parsers/Makefile.am.
XSD.  Created patches for all, added patches to redhawk-core recipe and attempted build again.
Received multiple errors regarding _skel_ files.  Errors pertain to parser routines expecting 3 arguments, but being given 4.  It appears that the XSD skel files in Bagoulla feature-no-xsd-1.10 are not compatible with the latest other cpp and headers from the master branch.

**Comment by btgoodwin** [comment]
We have a recipe for XSD over in [meta-redhawk-sdr](http://github.com/GeonTech/meta-redhawk-sdr) under `recipes-deps`.  The layer is a very distant cousin of openembedded-hawk from Axios, if you're interested in jumping up to REDHAWK 2.0.0.  We used our layer to load 2.0 onto an Ettus E310 a while back without having to resort to deep patches of the core framework.

The XSD recipe in ours can probably just be dropped into your layer, but you'll need to add `xsd-native` and `xsd` as a `DEPENDS`/`RDEPENDS` (for `-native` and headers, respectively, see our `framework-core` recipe for an example).  It'll load the XSD executable into the native side of the build and the headers into the machine.  Then your `configure` should be able to find what it needs.  

> Note: On occasion, bitbake fails to deploy `xsdcxx` to the x86 sysroot.  If this happens, try `bitbake -c build xsd` and check again.  We're looking into why it behaves like that occasionally but have not come up with a satisfactory fix at this time.

**Comment by bagoulla** [comment]
@horn545 I've updated the openembedded work for 2.0.1 to include the xsd recipes from the geon fork. I've also added a number of nice utilities to create a lightweight (C++ only) framework / GPP install and done some limited testing with the latest poky release. I'll do some additional testing this weekend but let me know if you have any issues via comments in that repo.
