### ISSUE TITLE
nodeBooter Error

### ISSUE THREAD

**Issue by kylecavs** [RedhawkSDR/framework-core#33]
Hi,

I am trying to build redhawk-src-2.1.0, but failing when building nodeBooter. The error log is shown below: 

./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::assign(char const*, char const*, unsigned int)':
/usr/include/boost/regex/v4/basic_regex.hpp:382: undefined reference to `boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int)'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::unwind_extra_block(bool)':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:1117: undefined reference to `boost::re_detail::put_mem_block(void*)'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `boost::re_detail::cpp_regex_traits_implementation<char>::error_string(boost::regex_constants::error_type) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:447: undefined reference to `boost::re_detail::get_default_error_string(boost::regex_constants::error_type)'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `void boost::re_detail::raise_error<boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > >(boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::error_type)':
/usr/include/boost/regex/pattern_except.hpp:75: undefined reference to `boost::re_detail::raise_runtime_error(std::runtime_error const&)'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `boost::re_detail::cpp_regex_traits_implementation<char>::error_string(boost::regex_constants::error_type) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:445: undefined reference to `boost::re_detail::get_default_error_string(boost::regex_constants::error_type)'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `save_state_init':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:107: undefined reference to `boost::re_detail::get_mem_block()'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find_imp()':
/usr/include/boost/regex/v4/perl_matcher_common.hpp:294: undefined reference to `boost::re_detail::verify_options(unsigned int, boost::regex_constants::_match_flags)'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `~save_state_init':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:115: undefined reference to `boost::re_detail::put_mem_block(void*)'
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:115: undefined reference to `boost::re_detail::put_mem_block(void*)'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `perl_matcher':
/usr/include/boost/regex/v4/perl_matcher.hpp:374: undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `boost::cpp_regex_traits<char>::transform_primary(char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:923: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `boost::cpp_regex_traits<char>::transform(char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:919: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::extend_stack()':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:213: undefined reference to `boost::re_detail::get_mem_block()'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_prefix()':
/usr/include/boost/regex/v4/perl_matcher_common.hpp:333: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
./.libs/libossiedomain.a(libossiedomain_la-helperFunctions.o): In function `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_match()':
/usr/include/boost/regex/v4/perl_matcher_non_recursive.hpp:973: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [nodeBooter] Error 1
make[2]: Leaving directory `/home/karma/redhawk/redhawk-src-2.1.0/redhawk/src/control/framework'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/karma/redhawk/redhawk-src-2.1.0/redhawk/src/control'
make: *** [all-recursive] Error 1

Thanks!

**Comment by shmahon** [comment]
Can you indicate what OS you are compiling on and list the boost packages that you have installed; something like the output of:

`rpm -qa | grep boost`

**Comment by kylecavs** [comment]
Thanks for the quick reply. I am compiling on Ubuntu 14.04 and have Boost Version: 1.54.0.1.

**Comment by btgoodwin** [comment]
@kylecavs I have not seen that specific error since I have not compiled 2.1 from source, however I have a working build from source for REDHAWK 2.0.5 in Ubuntu 16.04, if that helps.  It's part of [our Docker-REDHAWK Ubuntu Edition](http://github.com/GeonTech/docker-redhawk-ubuntu).  Perhaps the related [build scripts](https://github.com/Geontech/docker-redhawk-ubuntu/tree/master/Dockerfiles/files/build) might help?

For example, what steps are you following for compiling the source?  If you can, please try (from a cleaned source location):

```
$> ./reconf
$> ./configure CXXFLAGS="-fpermissive"
$> make
#> make install
```
 > Edit: I should point out that if your base OS is Ubuntu and you're simply wanting to have REDHAWK running locally with access to a workspace, IDE, etc. like a typical CentOS host installation, the regular [Docker-REDHAWK](http://github.com/GeonTech/docker-redhawk) installation uses CentOS 7 as the base OS of the containers so that anything you produce can run on a standard CentOS 7 domain.

**Comment by bagoulla** [comment]
@kylecavs This is an issue with the linker flags and the order they are in for the nodeBooter Makefile.am see the diff below and let me know if this does not fix the issue for you. Thanks for catching this issue!

The reason this is not seen in CentOS6 is that the version of gcc / g++ is newer and stricter with some of the rules.

```
diff --git a/redhawk/src/control/framework/Makefile.am b/redhawk/src/control/framework/Makefile.am
index 46506fa7..eaa94cc1 100644
--- a/redhawk/src/control/framework/Makefile.am
+++ b/redhawk/src/control/framework/Makefile.am
@@ -37,7 +37,7 @@ libossiedomain_la_LDFLAGS = -Wall
 bin_PROGRAMS = nodeBooter
 nodeBooter_SOURCES = nodebooter.cpp
 nodeBooter_CXXFLAGS = $(BOOST_CPPFLAGS)
-nodeBooter_LDADD = $(BOOST_LDFLAGS) $(BOOST_FILESYSTEM_LIB)  $(BOOST_REGEX_LIB) $(BOOST_SYSTEM_LIB) ../parser/libossieparser.la ./libossiedomain.la $(top_builddir)/base/framework/libossiecf.la $(top_builddir)/base/framework/idl/libossieidl.la  $(OMNICOS_LIBS) $(OMNIORB_LIBS)
+nodeBooter_LDADD = ../parser/libossieparser.la ./libossiedomain.la $(top_builddir)/base/framework/libossiecf.la $(top_builddir)/base/framework/idl/libossieidl.la $(BOOST_LDFLAGS) $(BOOST_FILESYSTEM_LIB) $(BOOST_SYSTEM_LIB) $(BOOST_REGEX_LIB) $(OMNICOS_LIBS) $(OMNIORB
_LIBS)
 nodeBooter_LDFLAGS = -static
 bin_SCRIPTS = nodeCleanup.py
```

**Comment by kylecavs** [comment]
@bagoulla  That seemed to fix the issue, thanks! Now just running into another issue, but I think it is related to your solution.

  CXXLD    ComponentHost
/usr/bin/ld: ComponentHost-ModuleLoader.o: undefined reference to symbol '_ZN5boost10filesystem6detail
13dir_itr_closeERPvS3_'
//usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.54.0: error adding symbols: DSO missing from comma
nd line
collect2: error: ld returned 1 exit status
make[3]: *** [ComponentHost] Error 1
make[3]: Leaving directory `/home/karma/redhawk/redhawk-src-2.1.0/redhawk/src/control/sdr/ComponentHos
t'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/karma/redhawk/redhawk-src-2.1.0/redhawk/src/control/sdr'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/karma/redhawk/redhawk-src-2.1.0/redhawk/src/control'
make: *** [all-recursive] Error 1

**Comment by kylecavs** [comment]
Changing Makefile.am in ComponentHost to what's shown below fixed the issue.
ComponentHost_SOURCES = ComponentHost.cpp ModuleLoader.cpp main.cpp
ComponentHost_CPPFLAGS = -I$(top_srcdir)/base/include $(BOOST_CPPFLAGS)
ComponentHost_CXXFLAGS = -Wall
ComponentHost_LDADD = $(top_builddir)/base/framework/libossiecf.la $(top_builddir)/base/framework/idl/libossieidl.la $(BOOST_LDFLAGS) $(BOOST_THREAD_LIB) $(BOOST_SYSTEM_LIB) $(BOOST_REGEX_LIB) 
ComponentHost_LDFLAGS = -static
