### ISSUE TITLE
bluefile.py

### ISSUE THREAD

**Issue by gmabey** [RedhawkSDR/framework-core#34]
Hello,

I have ported `bluefile.py` to python3, and I would like to contribute it to this project: https://github.com/gnuradio/SigMF since this project seems ... staleish.  There is any prospect for getting permission to do that?

**Comment by shmahon** [comment]
Not "staleish".  Deprecated.  Sorry for the unacceptably long delay in responding, but, as you noted, this project is not actively monitored.  Yes, please feel free to make use of this LGPL licensed repository as you find useful.  Just include a header that designates the LGPL license and copyright assignment.   Something like the following is offered as a template for your convenience:

```
/* 
 * This file contains code that was borrowed from REDHAWK SDR.
 * 
 * This is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software
 * Foundation.
 * 
 * This software is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
 * PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 * 
 * Copyright: mixed. See  [REDHAWK Github Project](https://github.com/RedhawkSDR/framework-core/tree/master/src) for copyright and licensing information.
 */ 
```
